query me {
  myInfo: me {
    id
    username
    email
    firstName
    lastName
    invitaciones: invitacionproyectoSet {
      id
      estado
      estadoStr
      proyecto {
        id
        titulo
        codigo
        categoria {
          id
          nombre
        }
      }
    }
  }
}

query searchUsuarios($search: String!, $proyectoId: ID!) {
  search(search: $search, proyectoId: $proyectoId) {
    id
    username
    firstName
    lastName
    email
  }
}
