fragment EstadosLeadProyectoFragment on EstadoLeadType {
  id
  titulo
  descripcion
  color
  colorFondo
  orden
}

fragment CamposLeadFragment on CamposLeadType {
  id
  nombre
  descripcion
  tipo
  titulo
  padreId
}
fragment SubCamposLeadFragment on CamposLeadType {
  ...CamposLeadFragment
  subCampos {
    ...CamposLeadFragment
  }
}
