#import "./fragments.gql"

query getProyectoByUsuarioAndCodigo($codigo: String!) {
  proyecto: proyectoInvitado(codigo: $codigo) {
    id
    titulo
    descripcion
  }
}

query getProyectoById($pk: ID!) {
  proyecto: proyectoUsuario(pk: $pk) {
    id
    titulo
    codigo
    categoria {
      id
      nombre
    }
  }
}

query getProyectoAndEstadosById($pk: ID!) {
  proyecto: proyectoUsuario(pk: $pk) {
    id
    titulo
    codigo
    estados {
      ...EstadosLeadProyectoFragment
      estados: estadoleadSet {
        ...EstadosLeadProyectoFragment
        estadoPadre {
          id
        }
      }
    }
  }
}

query getProyectoAndLeadGroupConfigs($pk: ID!) {
  proyecto: proyectoUsuario(pk: $pk) {
    id
    titulo
    codigo
    grupos: configuraciongrupoleadSet {
      id
      codigo
      titulo
      descripcion
      orden
    }
  }
}
