#import "./fragments.gql"

query getProyectoByUsuarioAndCodigo($codigo: String!) {
  proyecto: proyectoInvitado(codigo: $codigo) {
    id
    titulo
    descripcion
    iamAdmin
  }
}

query getProyectoById($pk: ID!) {
  proyecto: proyectoUsuario(pk: $pk) {
    id
    titulo
    codigo
    categoria {
      id
    }
  }
}

query getProyectoAndEstadosById($pk: ID!) {
  proyecto: proyectoUsuario(pk: $pk) {
    id
    titulo
    codigo
    estados {
      ...EstadosLeadProyectoFragment
      estados: estadoleadSet {
        ...EstadosLeadProyectoFragment
        estadoPadre {
          id
        }
      }
    }
  }
}

query getProyectoAndLeadGroupConfigs($pk: ID!) {
  proyecto: proyectoUsuario(pk: $pk) {
    id
    titulo
    codigo
    grupos: configuraciongrupoleadSet {
      id
      codigo
      titulo
      descripcion
      orden
    }
  }
}

query getInfoProyectoUsuario($pk: ID!) {
  proyecto: proyectoUsuario(pk: $pk) {
    id
    titulo
    codigo
  }
}

query getProyectoAndLeadGroupConfigsCampos($pk: ID!) {
  proyecto: proyectoUsuario(pk: $pk) {
    id
    titulo
    codigo
    grupos: configuraciongrupoleadSet {
      id
      label
    }
  }
}

query getCamposByGroupId($groupId: ID!) {
  camposPadre(grupoId: $groupId) {
    ...CamposLeadFragment
  }

  campos(grupoId: $groupId) {
    ...CamposLeadFragment
    subCampos {
      ...SubCamposLeadFragment
    }
  }
}

query getInvitacionesProyecto($proyectoId: ID!) {
  invitaciones(proyectoId: $proyectoId) {
    id
    estadoStr
    usuario {
      id
      username
      firstName
      lastName
    }
  }
}

query getMisInvitaciones {
  misInvitaciones {
    id
    estadoStr
    createdAt
    usuario {
      id
    }
    proyecto {
      id
      titulo
      administrador {
        username
        firstName
        lastName
      }
    }
  }
}

query getMisProyectos {
  proyectos: misProyectos {
    id
    titulo
    codigo
    categoria {
      id
      nombre
    }
  }
}

query getCredencialesByProyecto($proyectoId: ID!) {
  credenciales: credencialesEsternasProyecto(proyectoId: $proyectoId) {
    id
    nombre
    codigo
    descripcion
    isActive
  }
}
