query getProyectoByUsuarioAndCodigo($codigo: String!) {
  proyecto: proyectoInvitado(codigo: $codigo) {
    id
    titulo
    descripcion
  }
}

query getProyectoById($pk: ID!) {
  proyecto: proyectoUsuario(pk: $pk) {
    id
    titulo
    codigo
    categoria {
      id
      nombre
    }
  }
}
